# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 13:50
from __future__ import unicode_literals

import aldryn_redirects.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('aldryn_redirects', '0002_on_delete_and_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_route', models.CharField(db_index=True, help_text='Redirect origin. Do not provide the domain. Always add a leading slash here.', max_length=255, validators=[aldryn_redirects.validators.validate_inbound_route], verbose_name='Redirect from')),
                ('outbound_route', models.CharField(help_text='Redirect destination. Domain is not required (defaults to inbound route domain).', max_length=255, validators=[aldryn_redirects.validators.validate_outbound_route], verbose_name='Redirect to')),
                ('sites', models.ManyToManyField(related_name='_staticredirect_sites_+', to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Static Redirects',
                'verbose_name': 'Static Redirect',
            },
        ),
        migrations.CreateModel(
            name='StaticRedirectInboundRouteQueryParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('static_redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_params', to='aldryn_redirects.StaticRedirect')),
            ],
        ),
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ('old_path',), 'verbose_name': 'Multilanguage Redirect', 'verbose_name_plural': 'Multilanguage Redirects'},
        ),
        migrations.AlterModelOptions(
            name='redirecttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Multilanguage Redirect Translation'},
        ),
    ]
