# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_redirects', '0004_auto_20171208_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='changed_date',
            field=models.DateTimeField(auto_now=True, verbose_name='changed date'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticredirect',
            name='changed_date',
            field=models.DateTimeField(auto_now=True, verbose_name='changed date'),
        ),
        migrations.AddField(
            model_name='staticredirect',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
